---
- name: Logstash installation file
  copy: src=logstash-1.4.1-1_bd507eb.noarch.rpm dest=/home/ansible/files/ owner=ansible group=ansible mode=0644

- name: Logstash installed
  yum: name=/home/ansible/files/logstash-1.4.1-1_bd507eb.noarch.rpm state=installed

- name: Logstash config files
  copy: src=conf.d dest=/etc/logstash/ owner=root group=root mode=0644
  notify: restart logstash

#- name: Logstash start service
#  service: name=logstash enabled=yes

- include: assemble_iptables.yml

