---
- name: nginx repo
  copy: src=nginx.repo dest=/etc/yum.repos.d/ owner=root group=root
  register: nginxrepo

- name: refresh yum cache
  command: yum makecache
  when: nginxrepo.changed

- name: nginx installed
  yum: name=nginx state=installed

- name: signed certs
  synchronize: src=certs/ dest=/etc/pki/tls/certs/ copy_links=yes

- name: private keys
  copy: src=keys/{{ item }} dest=/etc/pki/tls/private/ owner=root group=root mode=0600
  with_items:
    - kibana.codeshelf.com.key
    - tsdb.codeshelf.com.key
    - grafana.codeshelf.com.key
    - dev.codeshelf.com.key
    - admin.codeshelf.com.key
    - tc.codeshelf.com.key
    - teamcity.codeshelf.com.key
    - codeshelfcom.key

- name: static sites
  synchronize: src=sites dest=/var/www

- name: nginx configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root mode=0644
  notify: reload nginx config

- name: nginx service
  service: name=nginx state=started

- include: assemble_iptables.yml

