---
- name: nginx repo
  copy: src=nginx.repo dest=/etc/yum.repos.d/ owner=root group=root
  register: nginxrepo

- name: refresh yum cache
  command: yum makecache
  when: nginxrepo.changed

- name: nginx installed
  yum: name=nginx state=installed

- name: signed certs
  synchronize: src=certs/ dest=/etc/pki/tls/certs/ copy_links=yes

- name: private keys
  copy: src=keys/{{ item }} dest=/etc/pki/tls/private/ owner=root group=root mode=0600
  with_items:
    - kibana.codeshelf.com.key
    - tsdb.codeshelf.com.key
    - grafana.codeshelf.com.key
    - dev.codeshelf.com.key
    - admin.codeshelf.com.key
    - tc.codeshelf.com.key
    - teamcity.codeshelf.com.key
    - productivity.codeshelf.com.key
    - codeshelfcom.key

- name: static sites
  synchronize: src=static dest=/var/www

- name: admin host list
  template: src=hosts.json.j2 dest=/var/www/static/admin/resources/hosts.json owner=root group=root mode=0644

- name: Got test site
  local_action: command /home/ansible/release/get_deployed.sh test
  sudo: False

- name: Got stage site
  local_action: command /home/ansible/release/get_deployed.sh stage
  sudo: False

- name: test site folder
  file: path=/var/www/test/ state=directory

- name: stage site folder
  file: path=/var/www/stage/ state=directory

- name: test site version
  copy: src=/home/ansible/release/CodeshelfUX/test/buildweb.txt dest=/var/www/test/
  register: uxtest

- name: stage site version
  copy: src=/home/ansible/release/CodeshelfUX/stage/buildweb.txt dest=/var/www/stage/
  register: uxstage

- name: test site installed
  unarchive: src=/home/ansible/release/CodeshelfUX/test/web_app.tgz dest=/var/www/test/
  when: uxtest.changed

- name: stage site installed
  unarchive: src=/home/ansible/release/CodeshelfUX/stage/web_app.tgz dest=/var/www/stage/
  when: uxstage.changed

- name: app browser config files
  template: src=websocket.addr.json.j2 dest=/var/www/{{ item }}/websocket.addr.json
  with_items:
    - test
    - stage

- name: nginx configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root mode=0644
  notify: reload nginx config

- name: nginx static password file
  copy: src=htpasswd dest=/etc/nginx/htpasswd owner=root group=root mode=0644 

- name: nginx service
  service: name=nginx state=started

- name: deploybot user
  user: name=deploybot generate_ssh_key=yes

- name: deploybot ssh key
  copy: src=id_deploybot dest=/home/deploybot/.ssh/id_rsa owner=deploybot group=deploybot mode=0600

- include: assemble_iptables.yml

