---
- name: nginx installed
  yum: name=nginx state=latest

- name: signed certs
  synchronize: src=certs/ dest=/etc/pki/tls/certs/ copy_links=yes

- name: private keys
  synchronize: src=keys/ dest=/etc/pki/tls/private/ copy_links=yes

- name: static sites
  synchronize: src=static dest=/var/www
  notify: dashboard directory permissions

- name: UX folders
  file: path=/var/www/cluster/ state=directory

- name: UX folders
  file: path=/var/www/cluster/ux/ state=directory

- name: UX versions
  copy: src=/home/ansible/master/release/CodeshelfUX/buildweb.txt dest=/var/www/cluster/
  register: ux

- name: UX HTML
  unarchive: src=/home/ansible/master/release/CodeshelfUX/web_app.tgz dest=/var/www/cluster/
  when: ux.changed

- name: app browser config files
  template: src=websocket.addr.json.j2 dest=/var/www/cluster/websocket.addr.json

- name: app browser config files
  template: src=websocket.addr.json.j2 dest=/var/www/cluster/ux/websocket.addr.json

- name: nginx configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root mode=0644
  notify: reload nginx config

- name: nginx static password file
  copy: src=htpasswd dest=/etc/nginx/htpasswd owner=root group=root mode=0644 

- name: nginx service
  service: name=nginx state=started enabled=yes

#- name: dashboard cron
#  cron: name="dashboard" minute="*/2" job="/var/www/static/dashboard/generate.sh 2>/dev/null >/dev/null" user=nginx

