---
- name: hadoop2 and hbase installation file
  unarchive: src=hbase-0.98.3-hadoop2-bin.tar.gz dest=/opt/ creates=/opt/hbase-0.98.3-hadoop2
  register: hbase

- name: hbase symlink
  file: state=link src=hbase-0.98.3-hadoop2 dest=/opt/hbase owner=root group=root

- name: hadoop2 and hbase single-host configuration
  copy: src=hbase-site.xml dest=/opt/hbase/conf/ owner=root group=root mode=0644
  notify: restart hbase

- name: hadoop user
  user: name=hadoop

- name: hadoop folder
  file: state=directory dest=/var/hadoop owner=hadoop group=hadoop mode=0755

- name: hadoop logs
  file: state=directory dest=/opt/hbase/logs/ owner=hadoop group=hadoop mode=0755

- name: hbase service symlink
  copy: src=hbase.service dest=/usr/lib/systemd/system/ owner=root group=root mode=0755
  register: hbase_service

#- name: systemctl daemon-reload
#  shell: systemctl daemon-reload
#  when: hbase_service.changed

- name: enable service
  service: name=hbase enabled=yes
  when: hbase_service.changed
  notify: restart hbase

- name: opentsdb installation file
  copy: src=opentsdb-2.1.0-ivan.noarch.rpm dest=/home/ansible/files/ owner=ansible group=ansible mode=0644
  register: opentsdb

- name: opentsdb installed
  yum: name=/home/ansible/files/opentsdb-2.1.0-ivan.noarch.rpm state=installed
  notify: restart opentsdb
  when: opentsdb.changed

- name: opentsdb user
  user: name=opentsdb

- name: init script to use opentsdb user
  lineinfile: dest=/usr/share/opentsdb/etc/init.d/opentsdb regexp="^USER=" insertafter="^HOSTNAME" line="USER=opentsdb"
  notify: restart opentsdb

- name: opentsdb /var/log permissions
  file: dest=/var/log/opentsdb state=directory owner=opentsdb group=opentsdb mode=0755

- name: opentsdb initialization
  shell: JAVA_HOME=/usr/java/default COMPRESSION=NONE HBASE_HOME=/opt/hbase /usr/share/opentsdb/tools/create_table.sh
  when: opentsdb.changed

- include: assemble_iptables.yml
