---
# copy restricted shell into place
- name: copy shell
  copy: src=restricted_shell dest=/bin/restricted_shell owner=root group=root mode=0555

- name: copy dummy shell
  copy: src=dummy_shell dest=/bin/dummy_shell owner=root group=root mode=0555

# user accounts
- name: set user accounts
  user: name={{ item }} shell=/bin/restricted_shell group=staff generate_ssh_key=yes
  with_items:
    - ayounts
    - reedwaller
    - pmonteiro
    - jranstrom
    - zach.gerstein
    - charlie.martin

# service accounts
- name: set service accounts
  user: name={{ item }} shell=/bin/dummy_shell group=staff generate_ssh_key=yes
  with_items:
    - matarea

# set up google-authenticator
- name: install google authenticator packages
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - libqrencode3
    - libpam-google-authenticator

- name: configure pam
  copy: src=pam_sshd dest=/etc/pam.d/sshd owner=root group=root mode=0444

- name: configure sshd
  copy: src=sshd_config dest=/etc/ssh/sshd_config owner=root group=root mode=0444
  notify:
    - reload sshd

