---
- name: basic management software installed
  yum: name={{ item }} state=installed
  with_items:
    - nrpe  
    - nagios-plugins-procs
    - nagios-plugins-pgsql
    - nagios-plugins-disk
    - nagios-plugins-users
    - nagios-plugins-log
    - nagios-plugins-swap
    - nagios-plugins-load
  notify:
    - restart nrpe

- name: nrpe.cfg
  copy: src=nrpe.cfg dest=/etc/nrpe owner=root group=root mode=0644
  notify:
    - restart nrpe

- name: iptables is running and enabled
  service: name=iptables state=started enabled=yes

- name: ferm firewall installed
  yum: name=ferm state=installed

- name: ferm main configuration folder
  file: path=/etc/ferm state=directory owner=root group=root mode=0700

- name: ferm additional configuration folder
  file: path=/etc/ferm/ferm.d state=directory owner=root group=root mode=0700

- name: ferm configuration file
  copy: src=ferm.conf dest=/etc/ferm/ferm.conf owner=root group=root mode=0600
  notify:
    - run ferm
    - save iptables
