---
# centos (base role) 
- name: Make sure that the ansible/files directory exsists
  file: path=/home/ansible/files/ state=directory

- name: Packages
  yum: name={{ item }} state=present
  with_items:
      - lsof
      - telnet
      - elinks
      - tmux
      - nrpe
      - vim
      - joe
      - nano
      - wget
      - libselinux-python
      - ntp
      - sudo
      - dstat
      - nagios-plugins-procs
      - nagios-plugins-pgsql
      - nagios-plugins-disk
      - nagios-plugins-users
      - nagios-plugins-log
      - nagios-plugins-swap
      - nagios-plugins-load

- name: ansible user authorized_keys
  copy: src=ansible_authorized_keys dest=/home/ansible/.ssh/authorized_keys owner=ansible mode=0444

- name: Ensure ntpd is running and enabled
  service: name=ntpd state=started enabled=yes

- name: Max files
  sysctl: name=fs.file-max value=512000 state=present reload=yes
  ignore_errors: yes  

- name: Userlimit files
  lineinfile: dest=/etc/security/limits.conf line="* - nofile 64000" insertafter=EOF

- name: nrpe.cfg
  copy: src=nrpe.cfg dest=/etc/nagios/nrpe.cfg owner=root group=root mode=0644
  notify:
    - restart nrpe

- name: nrpe enabled
  service: name=nrpe enabled=yes
  notify:
    - restart nrpe

- name: ip6tables service
  service: name=ip6tables enabled=yes state=started

- name: ip6tables configuration
  copy: src=ip6tables dest=/etc/sysconfig/ip6tables owner=root group=root mode=0400
  notify:
    - restart ip6tables

- name: iptables configuration assembly folder
  file: path=/etc/sysconfig/iptables.d state=directory owner=root group=root mode=0700

- name: JDK installation file
  copy: src=jdk-7u75-linux-x64.rpm dest=/home/ansible/files/ mode=0644

- name: JDK installed 
  yum: name=/home/ansible/files/jdk-7u75-linux-x64.rpm state=installed

- name: JAVA_HOME in profile
  copy: src=java.sh dest=/etc/profile.d/ owner=root group=root mode=0644

- name: Create swap space
  command: dd if=/dev/zero of=/xswap bs=1M count=2048
  when: ansible_swaptotal_mb < 500

- name: Make swap
  command: mkswap /xswap
  when: ansible_swaptotal_mb < 500

- name: swap in fstab
  lineinfile: dest=/etc/fstab regexp="^\/xswap" line="/xswap none swap sw 0 0" state=present

- name: configure swappiness in sysctl
  lineinfile: dest=/etc/sysctl.conf regexp="^vm.swappiness" line="vm.swappiness = 25" state=present
  register: config_swappiness

- name: change swappiness
  shell: "echo 25 > /proc/sys/vm/swappiness"
  when: config_swappiness.changed

- name: swap on
  command: swapon -a
  changed_when: False

- name: /etc/hosts
  template: src=hosts.j2 dest=/etc/hosts
  with_items:
  - "{{ inventory_hostname }}"

- name: Setup sudoers
  copy: src=sudoers dest=/etc/sudoers owner=root group=root mode=0440 validate='visudo -cf %s'

- name: rsyslog configuration
  copy: src=rsyslog.conf dest=/etc/ owner=root group=root mode=0644 
  notify:
    - restart rsyslog

- name: ssh moduli file copy
  copy: src=moduli dest=/etc/ssh/moduli owner=root group=root mode=0444

- include: assemble_iptables.yml

