---
- name: Make sure that the ansible/files directory exists
  file: path=/home/ansible/files/ state=directory

- name: Packages
  yum: name={{ item }} state=latest
  with_items:
      - epel-release
      - lsof
      - telnet
      - tmux
      - nrpe
      - vim
      - wget
      - libselinux-python
      - ntp
      - sudo
      - dstat
      - nagios-plugins-procs
      - nagios-plugins-pgsql
      - nagios-plugins-disk
      - nagios-plugins-users
      - nagios-plugins-log
      - nagios-plugins-swap
      - nagios-plugins-load

- name: upgrade operating system
  yum: name=* state=latest

- name: ansible user authorized_keys
  copy: src=ansible_authorized_keys dest=/home/ansible/.ssh/authorized_keys owner=ansible mode=0444

- name: Ensure ntpd is running and enabled
  service: name=ntpd state=started enabled=yes

- name: Max files
  sysctl: name=fs.file-max value=512000 state=present reload=yes
  ignore_errors: yes  

- name: Userlimit files
  lineinfile: dest=/etc/security/limits.conf line="* - nofile 64000" insertafter=EOF

- name: nrpe.cfg
  copy: src=nrpe.cfg dest=/etc/nagios/nrpe.cfg owner=root group=root mode=0644
  notify:
    - restart nrpe

- name: nrpe enabled
  service: name=nrpe enabled=yes
  notify:
    - restart nrpe

- name: ip6tables service
  service: name=ip6tables enabled=yes state=started

- name: ip6tables configuration
  copy: src=ip6tables dest=/etc/sysconfig/ip6tables owner=root group=root mode=0400
  notify:
    - restart ip6tables

- name: iptables configuration assembly folder
  file: path=/etc/sysconfig/iptables.d state=directory owner=root group=root mode=0700

- name: /etc/hosts
  template: src=hosts.j2 dest=/etc/hosts
  with_items:
  - "{{ inventory_hostname }}"

- name: Setup sudoers
  copy: src=sudoers dest=/etc/sudoers owner=root group=root mode=0440 validate='visudo -cf %s'

- name: rsyslog configuration
  copy: src=rsyslog.conf dest=/etc/ owner=root group=root mode=0644 
  notify:
    - restart rsyslog

- name: ssh moduli file copy
  copy: src=moduli dest=/etc/ssh/moduli owner=root group=root mode=0444

