---
- name: nrpe update
  hosts: DFW
  sudo: yes
  tasks:
    - name: nrpe installed
      yum: name={{ item }} state=latest
      with_items:
        - nrpe  
        - nagios-plugins-procs
        - nagios-plugins-pgsql
        - nagios-plugins-disk
        - nagios-plugins-users
        - nagios-plugins-log
        - nagios-plugins-swap
        - nagios-plugins-load

    - name: nrpe.cfg
      copy: src=roles/centos/files/nrpe.cfg dest=/etc/nagios/nrpe.cfg owner=root group=root mode=0644

    - name: restart nrpe
      service: name=nrpe state=restarted

