---
- name: reload iptables
  service: name=iptables state=restarted
  when: ansible_os_family == "RedHat"

- name: reload ip6tables
  service: name=ip6tables state=restarted
  when: ansible_os_family == "RedHat"

