---
- name: restart iptables
  service: name=iptables state=restarted

- name: restart ip6tables
  service: name=ip6tables state=restarted

- name: enforce firewall
  command: /etc/network/if-up.d/firewall

