---
# debian (base role)

# install some default packages
- name: default packages
  apt: name={{ item }} state=present
  with_items:
    - sudo
    - ethtool
    - pwgen
    - vim
    - lsof
    - tmux
    - ntp

# remove annoying packages
- name: blacklist packages
  apt: name={{ item }} state=absent
  with_items:
    - nano

# manage ntp
- name: Ensure ntp is started and enabled
  service: name=ntp state=started enabled=yes

- name: Configure ntp
  copy: src=ntp.conf dest=/etc/ntp.conf owner=root group=root mode=0444
  notify:
    - restart ntp

# manage motd
- name: remove default motd
  file: path=/etc/update.motd.d/{{ item }} state=absent
  with_items:
    - 00-header
    - 10-help-text
    - 91-release-upgrade

# manage ansible user
- name: Create ansible user
  user: name=ansible

- name: ansible authorized ssh keys
  copy: src=ansible_authorized_keys dest=/home/ansible/.ssh/authorized_keys owner=ansible mode=0444

- name: ansible files temporary directory
  file: path=/home/ansible/files/ state=directory

# manage sudoers
- name: sudoers configuration file
  copy: src=sudoers dest=/etc/sudoers owner=root group=root mode=0444

# manage sshd
- name: sshd configuration file
  copy: src=sshd_config dest=/etc/ssh/sshd_config owner=root group=root mode=0444
  notify:
    - restart ssh

- name: ssh moduli file copy
  copy: src=moduli dest=/etc/ssh/moduli owner=root group=root mode=0444

