---
- name: dialhome user account
  user: name=dialhome group=dialhome generate_ssh_key=yes ssh_key_bits=4096

- name: autossh package
  yum: name=autossh state=present
  when: ansible_os_family == "RedHat"

- name: autossh script
  template: src=autossh.sh.j2 dest=/home/dialhome/autossh.sh owner=dialhome group=dialhome mode=0700
  register: initscript

- name: autossh service
  copy: src=autossh.service dest=/usr/lib/systemd/autossh.service owner=root group=root mode=0755

- name: enable autossh service
  service: name=autossh enabled=yes
  when: initscript.changed
