---
- name: apache httpd with SSL
  yum: name=mod_ssl state=installed

- name: Certs
  copy: src=certs/{{ item }}  dest=/etc/pki/tls/certs/ owner=root group=root
  with_items:
    - codeshelf-ca.crt
    - kibana.codeshelf.com.crt
    - tsdb.codeshelf.com.crt
    - grafana.codeshelf.com.crt
    - dev.codeshelf.com.crt
    - admin.codeshelf.com.crt
    - tc.codeshelf.com.crt
    - teamcity.codeshelf.com.crt
    - codeshelfcom.crt

- name: Keys
  copy: src=keys/{{ item }} dest=/etc/pki/tls/private/ owner=root group=root mode=0600
  with_items:
    - kibana.codeshelf.com.key
    - tsdb.codeshelf.com.key
    - grafana.codeshelf.com.key
    - dev.codeshelf.com.key
    - admin.codeshelf.com.key
    - tc.codeshelf.com.key
    - teamcity.codeshelf.com.key
    - codeshelfcom.key

- name: main httpd config
  copy: src=httpd.conf dest=/etc/httpd/conf/ owner=root group=root mode=0644
  notify: restart httpd

- name: web configs
  copy: src=conf.d dest=/etc/httpd/ owner=root group=root mode=0644
  notify: restart httpd

- name: static sites
  synchronize: src={{ item }} dest=/var/www owner=no group=no delete=yes
  with_items:
    - dev
    - html
    - admin
    - mail
    - calendar
    - sites
    - drive
    - support
    - teamcity
    - grafana-1.8.1
    - kibana-3.1.0

- name: grafana symlink
  file: state=link src=grafana-1.8.1 dest=/var/www/grafana owner=root group=root

- name: kibana symlink
  file: state=link src=kibana-3.1.0 dest=/var/www/kibana owner=root group=root

- name: enable httpd service
  service: name=httpd enabled=yes

- include: assemble_iptables.yml

