---
- name: apache httpd with SSL
  yum: name=mod_ssl state=installed

- name: Certs
  copy: src=certs/{{ item }}  dest=/etc/pki/tls/certs/ owner=root group=root
  with_items:
    - codeshelf-ca.crt
    - GeoTrust_SSL_CA_G2_Cert_bundle.pem
    - kibana.codeshelf.com.crt
    - tsdb.codeshelf.com.crt
    - grafana.codeshelf.com.crt
    - dev.codeshelf.com.crt
    - admin.codeshelf.com.crt
    - codeshelfcom.crt

- name: Keys
  copy: src=keys/{{ item }} dest=/etc/pki/tls/private/ owner=root group=root mode=0600
  with_items:
    - kibana.codeshelf.com.key
    - tsdb.codeshelf.com.key
    - grafana.codeshelf.com.key
    - dev.codeshelf.com.key
    - admin.codeshelf.com.key
    - codeshelfcom.key

- name: default web content
  copy: src=default_html dest=/var/www/ owner=root group=root mode=0644

- name: main httpd config
  copy: src=httpd.conf dest=/etc/httpd/conf/ owner=root group=root mode=0644
  notify: restart httpd

- name: web configs
  copy: src=conf.d dest=/etc/httpd/ owner=root group=root mode=0644
  notify: restart httpd

- name: kibana app
  synchronize: src=kibana-3.1.0 dest=/var/www owner=no group=no delete=yes

- name: kibana symlink
  file: state=link src=kibana-3.1.0 dest=/var/www/kibana owner=root group=root

- name: grafana app
  synchronize: src=grafana-1.6.1 dest=/var/www owner=no group=no delete=yes

- name: dev site
  synchronize: src=dev dest=/var/www owner=no group=no delete=yes

- name: admin site
  synchronize: src=admin dest=/var/www owner=no group=no delete=yes

- name: grafana symlink
  file: state=link src=grafana-1.6.1 dest=/var/www/grafana owner=root group=root

- name: enable httpd service
  service: name=httpd enabled=yes

- include: assemble_iptables.yml

