---
- name: apache flume installer
  unarchive: src=apache-flume-1.6.0-bin.tar.gz dest=/opt/ creates=/opt/apache-flume-1.6.0-bin
  register: flume_installer

- name: flume user
  user: name=flume

- name: flume symlink
  file: state=link src=apache-flume-1.6.0-bin dest=/opt/flume owner=root group=root
  notify: restart flume

- name: flume config folder
  copy: src=flume dest=/etc/ owner=root group=root

- name: flume log folder
  file: state=directory path=/var/log/flume owner=flume group=flume

- name: flume channel folder
  file: state=directory path=/var/flume owner=flume group=flume

- name: flume properties
  template: src=flume-conf.properties.j2 dest=/etc/flume/flume-conf.properties owner=root group=root
  notify: restart flume

- name: flume extra libs
  copy: src=lib dest=/opt/flume/ owner=root group=root
  notify: restart flume

- name: flume service
  template: src=flume.conf.j2 dest=/etc/init/flume.conf owner=root group=root mode=0644
  notify: restart flume

- include: assemble_iptables.yml
