#!/bin/bash
#
# autossh – Startup script for autossh

# chkconfig: 2345 20 80
# description: Maintain a persistent SSH tunneling
# processname: autossh
# pidfile: /var/run/autossh.pid

# Source function library
. /etc/rc.d/init.d/functions

prog=autossh
autossh=/bin/autossh
RETVAL=0

start() {
SSHUSERNAME=provisioning
SSHRPORT=9999
echo -n Starting $prog, $SSHUSERNAME: 
su et -c "$autossh -f -M 0 \
	-TNn -i ~et/.ssh/id_rsa -p 8022 -o StrictHostKeyChecking=no \
	-o ConnectTimeout=20 -o ServerAliveInterval=20 \
	-R $SSHRPORT:127.0.0.1:22 $SSHUSERNAME@home1.codeshelf.com"
RETVAL=$?
[ $RETVAL -eq 0 ] && touch /var/lock/subsys/$prog
echo
echo $(pidof $prog) > /var/run/$prog.pid
return $RETVAL
}

stop() {
echo -n Stopping $prog: 
killproc $autossh
RETVAL=$?

[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$prog
return $RETVAL
}

case "$1" in
start)
start
;;
stop)
stop
;;
restart)
stop
start
;;
status)
status $autossh
RETVAL=$?
;;
*)
echo Usage: $0 {start\|stop\|restart\|status}
RETVAL=1
esac

exit $RETVAL

