---
- name: tcollector installation
  unarchive: src=tcollector_20140713.tgz dest=/usr/local/ creates=/usr/local/tcollector_20140713
  register: tcollector

- name: tcollector symlink
  file: state=link src=tcollector_20140713 dest=/usr/local/tcollector

- name: tcollector service
  file: state=link src=/usr/local/tcollector/rpm/initd.sh dest=/etc/init.d/tcollector owner=root group=root
  notify: restart tcollector

- name: set tsd host
  lineinfile: dest=/usr/local/tcollector/rpm/initd.sh regexp="^TSD_HOST" line="TSD_HOST=hadoop1"
  notify: restart tcollector

- name: service enable
  service: name=tcollector enabled=yes
  notify: restart tcollector
