---
- name: install postgresql redhat
  yum: name=postgresql-server state=installed
  when: ansible_os_family == "RedHat"
  register: pg

- name: run initdb
  command: /usr/bin/postgresql-setup initdb
  when: pg.changed

- name: install postgresql debian
  apt: name=postgresql state=installed
  when: ansible_os_family == "Debian"

- name: enable postgresql service
  service: name=postgresql state=started enabled=yes

# todo: create appropriate config files
# todo: create codeshelf + replicator users

