---
- name: Make sure that the ansible/files directory exsists
  action: file path=/home/ansible/files/ state=directory

- name: Check for Postgresql repo installation
  copy: src=pgdg-centos93-9.3-1.noarch.rpm dest=/home/ansible/files/ mode=0644
  register: pgrepo

- name: install postgres931 repo
  yum: name=/home/ansible/files/pgdg-centos93-9.3-1.noarch.rpm state=installed
  when: pgrepo.changed

- name: update yum cache
  command: yum makecache
  changed_when: False
  when: pgrepo.changed

- name: install postgresql server
  yum: name=postgresql93-server state=installed
  register: pg

- name: run initdb
  command: service postgresql-9.3 initdb
  when: pg.changed

- include: assemble_iptables.yml
