#!/usr/local/src/ansible/bin/ansible-playbook
---
- name: create hosts files
  hosts: DFW:localhost
  sudo: yes

  tasks:
  - lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item]['ansible_ssh_host'] }} {{item}}" state=present
#  - debug: msg="{{ hostvars[item]['ansible_ssh_host'] }} {{item}}"
    when: hostvars[item]['exclude_from_hosts'] is not defined and hostvars[item]['ansible_ssh_host'] is defined
    with_items: groups['all']
