---
- name: Codeshelf user
  user: name=codeshelf state=present

- name: Codeshelf home directory readable
  file: path=/home/codeshelf state=directory mode=0755

- name: Codeshelf local log file folder
  file: path=/home/codeshelf/.Codeshelf/ state=directory owner=codeshelf group=codeshelf mode=0755

- name: Codeshelf local log file folder (2)
  file: path=/home/codeshelf/.Codeshelf/logs/ state=directory owner=codeshelf group=codeshelf mode=0755

- name: Codeshelf configuration folder
  file: path=/etc/codeshelf/ state=directory owner=codeshelf group=codeshelf mode=0700

- name: Codeshelf installation folder
  file: path=/opt/codeshelf/ state=directory owner=codeshelf group=codeshelf mode=0755

- name: Codeshelf engine folder
  file: path=/opt/codeshelf/engine/ state=directory owner=codeshelf group=codeshelf mode=0755

- name: Codeshelf web folder
  file: path=/opt/codeshelf/web/ state=directory owner=codeshelf group=codeshelf mode=0755

- name: Codeshelf webapp folder
  file: path=/opt/codeshelf/web/app/ state=directory owner=codeshelf group=codeshelf mode=0755

- name: Keystore
  copy: src=etc_codeshelf/codeshelfcom.signed.keystore.jks dest=/etc/codeshelf/codeshelfcom.signed.keystore.jks owner=codeshelf group=codeshelf mode=0600

- name: codeshelf init script
  copy: src=codeshelf.service dest=/usr/lib/systemd/system/codeshelf.service owner=root group=root mode=0644
  register: initscript

- name: Enable service
  service: name=codeshelf enabled=yes
  when: initscript.changed

- name: codeshelf init helper
  template: src=codeshelf.engine.j2 dest=/opt/codeshelf/codeshelf.engine owner=root group=root mode=0755
  notify: Restart Fep

- name: App engine version
  copy: src=/home/ansible/master/release/Codeshelf/build.txt dest=/opt/codeshelf/ owner=codeshelf group=codeshelf mode=0644
  register: engine

- name: Configuration file from template
  template: src=server.config.properties.codeshelf.j2 dest=/etc/codeshelf/server.config.properties owner=codeshelf group=codeshelf mode=0600
  register: config

- name: Stop service
  service: name=codeshelf state=stopped
  when: engine.changed or config.changed or initscript.changed
  ignore_errors: yes

- name: Install app libraries
  unarchive: src=/home/ansible/master/release/Codeshelf/lib.tgz dest=/opt/codeshelf/engine/ owner=codeshelf group=codeshelf
  when: engine.changed

- name: Install app JAR
  copy: src=/home/ansible/master/release/Codeshelf/server.codeshelf.jar dest=/opt/codeshelf/engine/ owner=codeshelf group=codeshelf mode=0644
  when: engine.changed

- name: Start service
  service: name=codeshelf state=started
  when: engine.changed or config.changed or initscript.changed

