---
- name: Configure new temporary group
  hosts: tempservers
  gather_facts: False 
  vars:
    - ansiblepubkey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDc4mcehc00Id14sAe0H1HvRD2jh6DMVRXzrAF4Svu4QLZVvT5U43DNCCxfFZJcU9VYsWkME3L7Yd/Mjsml1nOCvlMWUvN57F2rqcY1/vDHO+5kVhsddD4gx1MH+uVtt8koT0LlH56Agv8nwMRorR2Del6Ec9mNTRQBQJ3q1Ga7zqqybvJiqPy0WdXh2BtQEwbVnET7Q9kJgH/RMlhDEPscycVktOwV48UMJdNye+4TGjkWFkh3G314p04X/drGr17iqYvXFatczjCJLhgoHEHShEdJTEvL4DPiROZ01XGrBHwvIUNdUFVm/SnqO1VdGjzjqa+ArgY1XVCEr9FVYih/ ansible

  vars_prompt:
    - name: "new_root_password"
      prompt: "root password (paste from password manager)"
      private: yes
      confirm: yes
      encrypt: "md5_crypt"
      salt_size: 7
      
  tasks:
    - name: pause
      local_action: 
        module: pause 
        minutes: 2 
        prompt: "waiting for new server to be responsive"

    - name: Create Ansible user
      user: name=ansible

    - name: Remove cloud-user
      user: name=cloud-user force=yes remove=yes state=absent

    - name: Authorize ansible
      authorized_key: 'key="{{ ansiblepubkey }}" user=ansible'  

    - name: Update packages
      yum: pkg=* state=latest

    - name: Install nrpe and utilities
      yum: name={{ item }} state=latest
      with_items:
      - vim
      - lsof
      - telnet
      - elinks
      - tmux
      - nrpe
      - nagios-plugins-procs
      - nagios-plugins-pgsql
      - nagios-plugins-disk
      - nagios-plugins-users
      - nagios-plugins-log
      - nagios-plugins-swap
      - nagios-plugins-load

    - name: Make sure that the ansible/files directory exsists
      file: path=/home/ansible/files/ state=directory

    - name: iptables configuration assembly folder
      file: path=/etc/sysconfig/iptables.d state=directory owner=root group=root mode=0700

    - name: Setup sudoers
      copy: src=/home/ansible/spinup/sudoers
             dest=/etc/sudoers
             owner=root group=root mode=0440
             validate='visudo -cf %s'

    - name: Configure SSHD
      copy: src=/home/ansible/spinup/sshd_config
             dest=/etc/ssh/sshd_config
             owner=root group=root mode=0600

    - name: Reboot in 1 minute
      shell: shutdown -r +1 "Ansible triggered" &

    - name: Set root password
      user: name=root password="{{ new_root_password }}"

    - name: Wait for SSH to come up on host
      local_action: wait_for "host={{ ansible_ssh_host }} port=22 state=started delay=65"
      sudo: false

# regenerate hosts files
#- include: updatehosts.yml
