---
- name: Configure new temporary group
  hosts: tempservers
  gather_facts: False 

  tasks:
    - name: Create Ansible user
      user: name=ansible

    - name: ansible/files folder
      file: path=/home/ansible/files/ state=directory owner=ansible group=ansible

    - name: Update packages
      yum: pkg=* state=latest
      when: ansible_os_family == "RedHat"

    - name: Update packages
      apt: pkg=* state=latest
      when: ansible_os_family == "Debian"

    - name: Install Ansible
      apt: name=ansible state=latest
      when: ansible_os_family == "Debian"

    - name: Make sure that the ansible/files directory exsists
      file: path=/home/ansible/files/ state=directory

    - name: Setup sudoers
      copy: src=/home/ansible/spinup/sudoers
             dest=/etc/sudoers
             owner=root group=root mode=0440
             validate='visudo -cf %s'
