---
- name: Logstash installation file
  copy: src=logstash-1.4.1-1_bd507eb.noarch.rpm dest=/home/ansible/files/ owner=ansible group=ansible mode=0644
  register: logstash

- name: Logstash installed
  yum: name=/home/ansible/files/logstash-1.4.1-1_bd507eb.noarch.rpm state=installed
  notify: restart logstash
  when: logstash.changed

- name: Logstash contrib plugins
  command: bin/plugin install contrib chdir=/opt/logstash/
  when: logstash.changed

- name: Patch msgpack codec
  copy: src=msgpack.rb dest=/opt/logstash/lib/logstash/codecs/ owner=logstash group=logstash mode=0664
  notify: restart logstash

- name: log4j2 plugin
  copy: src=lib dest=/opt/logstash/ owner=logstash group=logstash mode=0644

- name: log4j2 libs
  copy: src=vendor dest=/opt/logstash/ owner=logstash group=logstash mode=0644

- name: Patch service startup for HOSTNAME
  lineinfile: dest=/etc/init.d/logstash regexp="^export HOSTNAME" line="export HOSTNAME=`hostname`" state=present insertafter="END INIT INFO"
  notify: restart logstash

- name: Patch service startup for JAVA_HOME
  lineinfile: dest=/etc/init.d/logstash regexp="^\. /etc/profile.d/java\.sh" line=". /etc/profile.d/java.sh" state=present insertafter="export HOSTNAME"
  notify: restart logstash

#- name: Patch service startup for plugin
#  lineinfile: dest=/etc/init.d/logstash regexp="^LS_OPTS" line='LS_OPTS=" --pluginpath /opt/logstash/plugins/ "' state=present insertafter="LS_NICE"

- name: Logstash config files
  copy: src=conf.d dest=/etc/logstash/ owner=root group=root mode=0644
  notify: restart logstash

- name: Logstash patterns
  copy: src=patterns dest=/etc/logstash/ owner=root group=root mode=0644
  notify: restart logstash


