---
- name: Check for Elasticsearch repo installation
  copy: src=elasticsearch.repo dest=/etc/yum.repos.d/ owner=root group=root mode=0644
  register: rsrepo

- name: update yum cache
  command: yum makecache
  changed_when: False
  when: rsrepo.changed

- name: install Elasticsearch
  yum: name=elasticsearch state=installed

- name: ES data folder
  file: dest=/var/lib/elasticsearch/ state=directory owner=elasticsearch group=elasticsearch mode=0755

- name: setup xvde1
  lineinfile: dest=/etc/fstab regexp="^\/dev\/xvde1" line="/dev/xvde1 /var/lib/elasticsearch ext3 defaults,noatime,barrier=0 1 1" state=present
  when: rsrepo.changed

- name: create xvde1 fs
  command: /sbin/mkfs.ext3 /dev/xvde1
  when: rsrepo.changed

- name: mount xvde1
  command: /bin/mount /var/lib/elasticsearch
  when: rsrepo.changed

- name: Elasticsearch environment vars
  copy: src=sysconfig/elasticsearch dest=/etc/sysconfig/elasticsearch owner=root group=root mode=0644

- name: Elasticsearch config file
  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml owner=root group=root mode=0644

- name: enable Elasticsearch service
  service: name=elasticsearch enabled=yes state=started

- include: install_logstash.yml
- include: assemble_iptables.yml
