---
# centos handlers
- name: restart nrpe
  service: name=nrpe state=restarted

- name: restart rsyslog
  service: name=rsyslog state=restarted

- name: restart ip6tables
  service: name=ip6tables state=restarted

- name: restart gmond
  service: name=gmond state=restarted

- include: iptables_reload.yml

