---
# tc (teamcity server role)
- name: postgres database
  yum: name=postgresql-server state=present
  register: pg

- name: run initdb
  command: service postgresql initdb
  when: pg.changed

- name: enable postgresql service
  command: chkconfig postgresql on
  when: pg.changed

- name: start postgresql
  command: service postgresql start
  when: pg.changed

- name: teamcity user
  user: name=teamcity

- name: Installer file
  copy: src=TeamCity-8.1.5.tar.gz dest=/home/ansible/files/ mode=0644
  register: install

- name: Extract files
  command: tar -C /opt -xzf /home/ansible/files/TeamCity-8.1.5.tar.gz 
  when: install.changed

- name: file ownership
  command: chown -R teamcity:teamcity /opt/TeamCity
  when: install.changed

- name: Service script
  copy: src=teamcity dest=/etc/rc.d/init.d/ owner=root group=root mode=0755

- name: Service enabled
  service: name=teamcity enabled=true

- include: assemble_iptables.yml
