---
- name: restart logstash
  service: name=logstash state=stopped
  changed_when: True
  notify: start logstash

- name: start logstash
  service: name=logstash state=restarted

- name: restart elasticsearch
  service: name=elasticsearch state=stopped
  changed_when: True
  notify: start elasticsearch

- name: start elasticsearch
  service: name=elasticsearch state=restarted

- name: restart ssh
  service: name=sshd state=restarted

- name: restart autossh
  service: name=autossh state=restarted

